In [1]:
import pandas as pd 
df  = pd.read_csv("morocco_cities.csv")
df.head()

,city_name_en,city_name_ar,region,population_2024,area_km2,population_density,altitude_m,latitude,longitude,founded_year,is_capital,coast_city,climate
0,Casablanca,الدار البيضاء,Casablanca-Settat,4000000,386,10363,50,33.5731,-7.5898,1907,No,Yes,Semi-arid
1,Rabat,الرباط,Rabat-Salé-Kénitra,1900000,118,16102,75,34.0209,-6.8416,1146,Yes,Yes,Mediterranean
2,Fes,فاس,Fès-Meknès,1200000,320,3750,410,34.0333,-5.0000,789,No,No,Semi-arid
3,Marrakesh,مراكش,Marrakesh-Safi,1070000,230,4652,466,31.6295,-7.9811,1062,No,No,Hot semi-arid
4,Tangier,طنجة,Tanger-Tetouan-Al Hoceima,1065000,193,5518,50,35.7595,-5.8340,533,No,Yes,Mediterranean

In [9]:
df.shape

(40, 13)

In [2]:
df.tail()

,city_name_en,city_name_ar,region,population_2024,area_km2,population_density,altitude_m,latitude,longitude,founded_year,is_capital,coast_city,climate
35,Berkane,بركان,Oriental,120000,80,1500,250,34.9200,-2.3200,1953,No,No,Semi-arid
36,Taourirt,تاوريرت,Oriental,100000,90,1111,480,34.4088,-2.8944,1910,No,No,Semi-arid
37,Khemisset,الخميسات,Rabat-Salé-Kénitra,130000,85,1529,405,33.8244,-6.0656,1926,No,No,Semi-arid
38,Sidi Kacem,سيدي قاسم,Rabat-Salé-Kénitra,100000,70,1429,275,34.2261,-5.7128,1926,No,No,Semi-arid
39,Youssoufia,يوسفية,Marrakesh-Safi,80000,65,1231,365,32.2458,-8.5278,1954,No,No,Semi-arid

In [3]:
df.describe()

,population_2024,area_km2,population_density,altitude_m,latitude,longitude,founded_year
count,4.000000e+01,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000
mean,4.101250e+05,130.850000,2764.525000,426.275000,32.718103,-6.677515,1638.300000
std,7.015052e+05,77.327989,3007.191884,452.537574,2.428125,2.777681,437.927415
min,3.000000e+04,50.000000,91.000000,5.000000,23.684700,-15.957200,533.000000
25%,9.750000e+04,80.000000,900.500000,44.250000,31.600825,-8.112325,1429.500000
50%,1.400000e+05,100.000000,1764.500000,334.500000,33.345900,-6.111050,1908.500000
75%,3.625000e+05,157.250000,3970.000000,562.500000,34.234825,-5.193325,1931.250000
max,4.000000e+06,386.000000,16102.000000,1665.000000,35.759500,-1.908600,1971.000000